/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AiAndHumanRouteImport } from './routes/ai-and-human'
import { Route as FinancialLiteracyRouteImport } from './routes/financial-literacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ApiPublicImgRouteImport } from './routes/api/public/img'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAndHumanRoute = AiAndHumanRouteImport.update({
  id: '/ai-and-human',
  path: '/ai-and-human',
  getParentRoute: () => rootRouteImport,
} as any)
const FinancialLiteracyRoute = FinancialLiteracyRouteImport.update({
  id: '/financial-literacy',
  path: '/financial-literacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgRoute = ApiPublicImgRouteImport.update({
  id: '/api/public/img',
  path: '/api/public/img',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-and-human': typeof AiAndHumanRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/register': typeof RegisterRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-and-human': typeof AiAndHumanRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/register': typeof RegisterRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/ai-and-human': typeof AiAndHumanRoute
  '/financial-literacy': typeof FinancialLiteracyRoute
  '/register': typeof RegisterRoute
  '/api/public/img': typeof ApiPublicImgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/ai-and-human'
    | '/financial-literacy'
    | '/register'
    | '/api/public/img'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/ai-and-human'
    | '/financial-literacy'
    | '/register'
    | '/api/public/img'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/ai-and-human'
    | '/financial-literacy'
    | '/register'
    | '/api/public/img'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AiAndHumanRoute: typeof AiAndHumanRoute
  FinancialLiteracyRoute: typeof FinancialLiteracyRoute
  RegisterRoute: typeof RegisterRoute
  ApiPublicImgRoute: typeof ApiPublicImgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-and-human': {
      id: '/ai-and-human'
      path: '/ai-and-human'
      fullPath: '/ai-and-human'
      preLoaderRoute: typeof AiAndHumanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financial-literacy': {
      id: '/financial-literacy'
      path: '/financial-literacy'
      fullPath: '/financial-literacy'
      preLoaderRoute: typeof FinancialLiteracyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img': {
      id: '/api/public/img'
      path: '/api/public/img'
      fullPath: '/api/public/img'
      preLoaderRoute: typeof ApiPublicImgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AiAndHumanRoute: AiAndHumanRoute,
  FinancialLiteracyRoute: FinancialLiteracyRoute,
  RegisterRoute: RegisterRoute,
  ApiPublicImgRoute: ApiPublicImgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
